#ifndef PARSER_TABLE_DEFS
#define PARSER_TABLE_DEFS 


#define REDUCE 0x20000000
#define SHIFT  0x80000000
#define  ACCEPT 0x40000000
#define UNDEFINED 0xffffffff
enum e_Terminal{
	PARSER_SEMICOLON_TOKEN,
	PARSER_ASSIGN_TOKEN,
	PARSER_UNION_KEYWORD_TOKEN,
	PARSER_NAME_TOKEN,
	PARSER_LCURLY_TOKEN,
	PARSER_RCURLY_TOKEN,
	PARSER_STRUCT_KEYWORD_TOKEN,
	PARSER_ENUM_KEYWORD_TOKEN,
	PARSER_COMMA_TOKEN,
	PARSER_LSQUARE_TOKEN,
	PARSER_RSQUARE_TOKEN,
	PARSER_LPAREN_TOKEN,
	PARSER_RPAREN_TOKEN,
	PARSER_VOID_KEYWORD_TOKEN,
	PARSER_IF_KEYWORD_TOKEN,
	PARSER_ELSE_KEYWORD_TOKEN,
	PARSER_WHILE_KEYWORD_TOKEN,
	PARSER_DO_KEYWORD_TOKEN,
	PARSER_FOR_KEYWORD_TOKEN,
	PARSER_RETURN_KEYWORD_TOKEN,
	PARSER_CONTINUE_KEYWORD_TOKEN,
	PARSER_BREAK_KEYWORD_TOKEN,
	PARSER_GOTO_KEYWORD_TOKEN,
	PARSER_COLON_TOKEN,
	PARSER_SWITCH_KEYWORD_TOKEN,
	PARSER_CASE_KEYWORD_TOKEN,
	PARSER_DEFAULT_KEYWORD_TOKEN,
	PARSER_QUESTION_TOKEN,
	PARSER_LOGICALOR_TOKEN,
	PARSER_LOGICALAND_TOKEN,
	PARSER_BINOR_TOKEN,
	PARSER_XOR_TOKEN,
	PARSER_BINAND_TOKEN,
	PARSER_EQUALS_TOKEN,
	PARSER_NEQUALS_TOKEN,
	PARSER_LESSTHAN_TOKEN,
	PARSER_GREATERTHAN_TOKEN,
	PARSER_GEQ_TOKEN,
	PARSER_LEQ_TOKEN,
	PARSER_LEFTSHIFT_TOKEN,
	PARSER_RIGHTSHIFT_TOKEN,
	PARSER_PLUS_TOKEN,
	PARSER_MINUS_TOKEN,
	PARSER_STAR_TOKEN,
	PARSER_MOD_TOKEN,
	PARSER_FSLASH_TOKEN,
	PARSER_PLUSPLUS_TOKEN,
	PARSER_MINUSMINUS_TOKEN,
	PARSER_NOT_TOKEN,
	PARSER_COMPLEMENT_TOKEN,
	PARSER_SIZEOF_KEYWORD_TOKEN,
	PARSER_FULLSTOP_TOKEN,
	PARSER_ARROW_TOKEN,
	PARSER_INT_TOKEN,
	PARSER_STRING_TOKEN,
	PARSER_FLOAT_TOKEN,
	PARSER_CHAR_TOKEN,
	PARSER_PLUSEQUALS_TOKEN,
	PARSER_TIMESEQUALS_TOKEN,
	PARSER_FSLASHEQUALS_TOKEN,
	PARSER_MINUSEQUALS_TOKEN,
	PARSER_MODEQUALS_TOKEN,
	PARSER_UNSIGNED_KEYWORD_TOKEN,
	PARSER_INT_KEYWORD_TOKEN,
	PARSER_SHORT_KEYWORD_TOKEN,
	PARSER_LONG_KEYWORD_TOKEN,
	PARSER_FLOAT_KEYWORD_TOKEN,
	PARSER_CHAR_KEYWORD_TOKEN,
	PARSER_DOUBLE_KEYWORD_TOKEN,
	PARSER_EOF_TOKEN
};
typedef enum e_NonTerminal NonTerminal;
enum e_NonTerminal{
	PARSER_Program,
	PARSER_Stmts,
	PARSER_Stmt,
	PARSER_DeclAssign,
	PARSER_TypeDecl,
	PARSER_UnionDecl,
	PARSER_StructDecl,
	PARSER_EnumDecl,
	PARSER_EnumNames,
	PARSER_Members,
	PARSER_Decl,
	PARSER_FuncParamsList,
	PARSER_FuncParams,
	PARSER_Block,
	PARSER_Cases,
	PARSER_Case,
	PARSER_CaseLabel,
	PARSER_Expr,
	PARSER_AssignmentExpression,
	PARSER_TernaryExpression,
	PARSER_BinaryExpressionI,
	PARSER_BinaryExpressionII,
	PARSER_BinaryExpressionIII,
	PARSER_BinaryExpressionIV,
	PARSER_BinaryExpressionV,
	PARSER_BinaryExpressionVI,
	PARSER_BinaryExpressionVII,
	PARSER_BinaryExpressionVIII,
	PARSER_BinaryExpressionIX,
	PARSER_BinaryExpressionX,
	PARSER_UnaryExpressionI,
	PARSER_UnaryExpressionII,
	PARSER_UnaryExpressionIII,
	PARSER_Value,
	PARSER_AssignmentOperator,
	PARSER_ArgList,
	PARSER_Args,
	PARSER_Cast,
	PARSER_Type,
	PARSER_PrimitiveType
};
typedef enum e_Terminal Terminal;
typedef unsigned int Action;
typedef unsigned int ParserState;

#define NUM_RULES 125
#define NUM_STATES 1618
#define NUM_TERMINALS 70
#define NUM_NONTERMINALS 40


extern int ruleSizes[ NUM_RULES ];
extern NonTerminal reductions[ NUM_RULES ];
extern Action actionTable[ NUM_STATES ][ NUM_TERMINALS ];
extern ParserState gotoTable[ NUM_STATES ][ NUM_NONTERMINALS ];    
extern char* tokenNameTable[ 2 ][ NUM_TERMINALS > NUM_NONTERMINALS ? NUM_TERMINALS : NUM_NONTERMINALS ];


#endif
